# Generated by Django 2.1.7 on 2020-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdetails',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
